[tool.poetry]
name = "fileapi"
version = "0.1.0"
description = ""
authors = ["Shawn-callistus <shawn21110204@snuchennai.edu.in>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
